QUEUE_PROVIDER: 'shoryuken' # or sidekiq

# AWS for shoryuken SQS configuration
ENABLE_AWS: 'false'
AWS_REGION: ''
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''

# Sidekiq configuration
REDIS_HOST: ''
REDIS_PORT: ''
SIDEKIQ_NAMESPACE: ''

